## Get the rent offer by id
GET http://localhost:4000/rentOffers/65464c1b76a5aa758fc54245 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt1cnQuY29iYWluQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikt1cnQiLCJsYXN0TmFtZSI6IkNvYmFpbiIsImlkIjoiNjU0M2U3MzlhMWM0YzU1NGJmYjEwNjNiIiwiaWF0IjoxNjk4OTQ5MDA5LCJleHAiOjE2OTkxMjE4MDl9.n3YH8RvZO6PJ-jdc-3sKjSDvfaCDb4YduZUpD9yihZ4

###
## Get the list of rent offers
GET http://localhost:4000/rentOffers?limit=2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt1cnQuY29iYWluQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikt1cnQiLCJsYXN0TmFtZSI6IkNvYmFpbiIsImlkIjoiNjU0M2U3MzlhMWM0YzU1NGJmYjEwNjNiIiwiaWF0IjoxNjk4OTQ5MDA5LCJleHAiOjE2OTkxMjE4MDl9.n3YH8RvZO6PJ-jdc-3sKjSDvfaCDb4YduZUpD9yihZ4

###
## Create new offer
POST http://localhost:4000/rentOffers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4ubGVubm9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ikxlbm5vbiIsImlkIjoiNjU0MjRhNmZhYWZjYjE1OWE1MGVmMzg5IiwiaWF0IjoxNjk5MzA0NjQ0LCJleHAiOjE2OTk0Nzc0NDR9.fGH5GMi6B1ACVdaT1heeKxSVkFIoCy7XseoDLdQKrxI
Content-Type: application/json

{
  "title": "Cool offer ever",
  "description": "Cool offer ever description description",
  "publishDate": "2022-08-12T11:56:37.573Z",
  "preview": "cool-preview.png",
  "images": ["image1.jpg", "image2.jpg", "image3.jpg", "image4.jpg", "image5.jpg", "image6.jpg"],
  "isPremium": false,
  "isFavorite": false,
  "rating": 5,
  "rooms": 1,
  "guests": 2,
  "houseType": "Room",
  "price": 150,
  "features": ["Breakfast"],
  "cityId": "652c4d099cfb7741494f0d83",
  "latitude": 51.509865,
  "longitude": -0.118092
}

###
## Delete rent offer by id
DELETE http://localhost:4000/rentOffers/65469c4f89323f1e838e2e3e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4ubGVubm9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ikxlbm5vbiIsImlkIjoiNjU0MjRhNmZhYWZjYjE1OWE1MGVmMzg5IiwiaWF0IjoxNjk5MTI2Mzc5LCJleHAiOjE2OTkyOTkxNzl9.xjo7uI8L2ZnnsmgIp4gT7chT9xLmewnIu7gK0ori1Xk

###
## Update rent offer by id
PATCH http://localhost:4000/rentOffers/654693e4bf739f018e98ab4c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4ubGVubm9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ikxlbm5vbiIsImlkIjoiNjU0MjRhNmZhYWZjYjE1OWE1MGVmMzg5IiwiaWF0IjoxNjk5MTI0MTgwLCJleHAiOjE2OTkyOTY5ODB9.hdhIM9FcpN_emsXej_4gLl2_fJ7LNg3PtMZ6QStfhEA
Content-Type: application/json

{
  "isPremium": true
}


###
## Upload preview image for a specific rent offer
POST http://localhost:4000/rentOffers/6546acebf3e30d6c7af7a4e8/preview HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4ubGVubm9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ikxlbm5vbiIsImlkIjoiNjU0MjRhNmZhYWZjYjE1OWE1MGVmMzg5IiwiaWF0IjoxNjk5MzA0NjQ0LCJleHAiOjE2OTk0Nzc0NDR9.fGH5GMi6B1ACVdaT1heeKxSVkFIoCy7XseoDLdQKrxI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="hot-tube.png"
Content-Type: image/png

< /Users/antonpaskanny/Desktop/hot-tube.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
## Upload gallery images for a specific rent offer
POST http://localhost:4000/rentOffers/6546acebf3e30d6c7af7a4e8/images HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4ubGVubm9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ikxlbm5vbiIsImlkIjoiNjU0MjRhNmZhYWZjYjE1OWE1MGVmMzg5IiwiaWF0IjoxNjk5MzA0NjQ0LCJleHAiOjE2OTk0Nzc0NDR9.fGH5GMi6B1ACVdaT1heeKxSVkFIoCy7XseoDLdQKrxI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image1.png"
Content-Type: image/png

< /Users/antonpaskanny/Desktop/image1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image2.png"
Content-Type: image/png

< /Users/antonpaskanny/Desktop/image2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image3.png"
Content-Type: image/png

< /Users/antonpaskanny/Desktop/image3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
## Get rent offers from a specific city
GET http://localhost:4000/cities/652c4d099cfb7741494f0d83/rentOffers?limit=10 HTTP/1.1

###
## Get premium rent offers from a specific city
GET http://localhost:4000/cities/652c4d099cfb7741494f0d83/rentOffers/premium HTTP/1.1

###
## Get list of comments to a specifit rent offer
GET http://localhost:4000/rentOffers/65464c1b76a5aa758fc54245/comments HTTP/1.1

###

## Get all favorite rent offers
GET http://localhost:4000/rentOffers/favorite/all HTTP/1.1
