export const DEFAULT_OFFER_COUNT = 60;
export const DEFAULT_DISCUSSED_OFFER_COUNT = 5;
export const DEFAULT_NEW_OFFER_COUNT = 5;
export const MAX_PREMIUM_OFFERS_COUNT = 3;
export const MAX_OFFER_IMAGES = 3;
