## Get the rent offer by id
GET http://localhost:4000/rentOffers/652c5693a131ff6e3e8e4f8f HTTP/1.1

###

## Get the list of rent offers
GET http://localhost:4000/rentOffers HTTP/1.1

###

## Create new offer
POST http://localhost:4000/rentOffers HTTP/1.1
Content-Type: application/json

{
  "title": "Test title",
  "description": "Test description",
  "publishDate": "2022-05-12T11:56:37.573Z",
  "preview": "test-preview.png",
  "features": ["image1.jpg", "image2.jpg"],
  "isPremium": false,
  "isFavourite": false,
  "rating": 7,
  "rooms": 5,
  "guests": 8,
  "houseType": "House",
  "price": 1408,
  "features": ["Laptop", "Washer"],
  "authorId": "652c5693a131ff6e3e8e4f99",
  "cityId": "652c5693a131ff6e3e8e4777"
}

###

## Delete rent offer by id

DELETE http://localhost:4000/rentOffers/111c5693a131ff6e3e8e4f96 HTTP/1.1

###

## Update rent offer by id

PATCH http://localhost:4000/rentOffers/652c5693a131ff6e3e8e4f96 HTTP/1.1
Content-Type: application/json

{
  "title": "Updated title",
  "description": "Updated description",
  "price": 999
}

###
## Get rent offers from a specific city

GET http://localhost:4000/cities/652c4d7bdbb8c5afbade2be0/rentOffers?limit=10 HTTP/1.1

###

###
## Get premium rent offers from a specific city

GET http://localhost:4000/cities/652c4d7bdbb8c5afbade2be0/rentOffers/premium HTTP/1.1

###

## Get list of comments to a specifit rent offer
GET http://localhost:4000/rentOffers/628a27d729c45f2bf9f6806a/comments HTTP/1.1

###
