
# Users
## Create new user

POST http://localhost:4000/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "trump.donald@gmail.com",
  "avatarPath": "trump.png",
  "firstName": "Donald",
  "lastName": "Trump",
  "password": "trumptower",
  "type": "Pro"
}

###

## Sign In

POST http://localhost:4000/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "john.lennon@gmail.com",
  "password": "imagine"
}

###

## Send avatar image

POST http://localhost:4000/users/652c5693a131ff6e3e8e4f8c/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/antonpaskanny/Desktop/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Check user's token
GET http://localhost:4000/users/signin HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt1cnQuY29iYWluQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikt1cnQiLCJsYXN0TmFtZSI6IkNvYmFpbiIsImlkIjoiNjU0M2U3MzlhMWM0YzU1NGJmYjEwNjNiIiwiaWF0IjoxNjk4OTQ5MDA5LCJleHAiOjE2OTkxMjE4MDl9.n3YH8RvZO6PJ-jdc-3sKjSDvfaCDb4YduZUpD9yihZ4

###
## Get list of favorite offers for a specific user
GET http://localhost:4000/users/rentOffers/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4ubGVubm9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ikxlbm5vbiIsImlkIjoiNjU0MjRhNmZhYWZjYjE1OWE1MGVmMzg5IiwiaWF0IjoxNjk5MTI0MTgwLCJleHAiOjE2OTkyOTY5ODB9.hdhIM9FcpN_emsXej_4gLl2_fJ7LNg3PtMZ6QStfhEA

###
## Add rent offer to a favorite list
POST http://localhost:4000/users/rentOffers/65464c1b76a5aa758fc54245/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4ubGVubm9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ikxlbm5vbiIsImlkIjoiNjU0MjRhNmZhYWZjYjE1OWE1MGVmMzg5IiwiaWF0IjoxNjk5MTI0MTgwLCJleHAiOjE2OTkyOTY5ODB9.hdhIM9FcpN_emsXej_4gLl2_fJ7LNg3PtMZ6QStfhEA

###
## Remove rent offer from a favorite list
DELETE http://localhost:4000/users/rentOffers/65464c1b76a5aa758fc54245/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4ubGVubm9uQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6Ikxlbm5vbiIsImlkIjoiNjU0MjRhNmZhYWZjYjE1OWE1MGVmMzg5IiwiaWF0IjoxNjk5MTI0MTgwLCJleHAiOjE2OTkyOTY5ODB9.hdhIM9FcpN_emsXej_4gLl2_fJ7LNg3PtMZ6QStfhEA


