
# Users
## Create new user

POST http://localhost:4000/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "john.lennon@gmail.com",
  "avatarPath": "test-avatar.png",
  "firstName": "John",
  "lastName": "Lennon",
  "password": "imagine",
  "type": "Pro"
}

###

## Sign In

POST http://localhost:4000/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "john.lennon@gmail.com",
  "password": "imagine"
}

###

## Send avatar image

POST http://localhost:4000/users/652c5693a131ff6e3e8e4f8c/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/antonpaskanny/Desktop/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Check user's token
GET http://localhost:4000/users/signin HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0NzBiYzM4M2UzMGRiNjc5ZGZhYzJkMiIsImlhdCI6MTY4NTk3NTQ4MiwiZXhwIjoxNjg2MTQ4MjgyfQ.Gq2-B1egouAnMxmXlR2ElVT6wCa97PS6lxzVI8LnGvo

###
## Get list of favorite offers for a specific user
GET http://localhost:4000/users/65424a6faafcb159a50ef389/rentOffers/favorite HTTP/1.1

###
## Add rent offer to a favorite list
POST http://localhost:4000/users/65424a6faafcb159a50ef389/rentOffers/652c5693a131ff6e3e8e4f96/favorite HTTP/1.1

###
## Remove rent offer from a favorite list
DELETE http://localhost:4000/users/65424a6faafcb159a50ef389/rentOffers/652c5693a131ff6e3e8e4f96/favorite HTTP/1.1


